name: go-test
description: |
  This action tests and lints Go code in a repository.
  It includes unit tests, Go linting, YAML linting, and vulnerability scanning using Trivy.
  The action is designed to be reusable across different workflows.

inputs:
  go-version:
    description: 'Version of Go to use'
    required: false
    default: '1.25.0'
  scan-severity:
    description: 'Trivy scan severity'
    required: false
    default: 'CRITICAL,HIGH'
  linter-version:
    description: 'Version of golangci version to use'
    required: false
    default: v2.4.0
  yaml-linter-config-path:
    description: 'Path to the YAML linter config file'
    required: false
    default: '.yamllint'
  go-linter-config-path:
    description: 'Path to the Go linter config file'
    required: false
    default: '.golangci.yaml'

runs:
  using: "composite"

  steps:

  # Setup Environment
  - name: Checkout Code
    uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
  - name: Setup Go
    uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v6.0.0
    with:
      go-version: '${{ inputs.go-version }}'
      cache: true
      cache-dependency-path: |
        go.sum
        **/go.sum

  # Unit Tests
  - name: Tidy Modules
    shell: bash
    run: |
      go version
      go mod tidy
  - name: Unit Test
    shell: bash
    run: |
      go test -count=1 -covermode=atomic -coverprofile=coverage.out ./...
      go tool cover -func=coverage.out
  - name: Parse Coverage
    uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7  # v5.5.1
    with:
      fail_ci_if_error: true
      use_oidc: true

  # Lint Code
  - name: Config Go Lint
    id: golangci_config
    uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6  # v3.0.0
    with:
      files: ${{ inputs.go-linter-config-path }}
  - name: Lint Go
    if: steps.golangci_config.outputs.files_exists == 'true'
    uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9  # v8.0.0
    with:
      version: ${{ inputs.linter-version }}
  - name: Config YAML Lint
    id: yamllint_config
    uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6  # v3.0.0
    with:
      files: ${{ inputs.yaml-linter-config-path }}
  - name: Lint YAML
    if: steps.yamllint_config.outputs.files_exists == 'true'
    uses: karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2  # v3.0.0
    with:
      yamllint_config_filepath: ${{ inputs.yaml-linter-config-path }}

  # Scan for Vulnerabilities
  - name: Scan Repo
    uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8  # v0.33.1
    with:
      scan-type: 'fs'
      ignore-unfixed: true
      hide-progress: true
      format: 'sarif'
      output: 'trivy-results.sarif'
      severity: ${{ inputs.scan-severity }}
      exit-code: '1'
  - name: Upload Report
    uses: github/codeql-action/upload-sarif@16df4fbc19aea13d921737861d6c622bf3cefe23  # v2.23.0
    with:
      sarif_file: 'trivy-results.sarif'