name: attest
description: |
  Attest container images using SLSA provenance and cosign


inputs:
  image-uri:
    description: 'Fully-qualified image URI to verify (registry/image@sha256:digest)'
    required: true
  cosign-version:
    description: 'The version of cosign to use'
    required: false
    default: 'v2.5.0'

runs:
  using: "composite"

  steps:

  - uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ${{ needs.conf.outputs.image }}
      digest: ${{ needs.conf.outputs.digest }}
      registry-username: ${{ github.actor }}
      secrets:
        registry-password: ${{ secrets.GITHUB_TOKEN }}

  - name: Install Cosign
    uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159  # v3.9.2
    with:
      cosign-release: ${{ inputs.cosign-version }}

  - name: Auth Cosign
    shell: bash
    run: |
      cosign login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

  # SLSA provenance verification using cosign and CUE policy.
  - name: Verify SLSA Provenance (cosign)
    shell: bash
    run: |
      cosign verify-attestation \
        --type slsaprovenance \
        --certificate-identity-regexp "^https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@refs/tags/v[0-9]+.[0-9]+.[0-9]+$" \
        --certificate-oidc-issuer https://token.actions.githubusercontent.com \
        --policy policy/provenance.cue \
        ${{ inputs.image-uri }}

  - uses: slsa-framework/slsa-verifier/actions/installer@ea584f4502babc6f60d9bc799dbbb13c1caa9ee6  # v2.7.1

  # SLSA provenance verification using slsa-verifier.
  - name: Verify SLSA Provenance (slsa-verifier)
    shell: bash
    run: |-
      slsa-verifier verify-image ${{ inputs.image-uri }} \
        --source-uri "github.com/$GITHUB_REPOSITORY" \
        --source-tag "$GITHUB_REF_NAME"