name: sign-keyless
on:
  workflow_call:
    inputs:
      image-uri:
        description: 'Fully-qualified image digest to verify (registry/image@sha256:digest)'
        required: true
        type: string
      cosign-version:
        description: 'The version of cosign to use'
        required: false
        type: string
        default: 'v2.0.1'
      image-tag:
        description: 'Image tag to verify (registry/image:tag)'
        required: false
        type: string
        default: 'latest'

jobs:
  sign-keyless:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: write
      id-token: write  # Needed for OIDC and keyless signing
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159  # v3.9.2
        with:
          cosign-release: ${{ inputs.cosign-version }}
      - name: Check Cosign
        run: |
          cosign version
      - name: Auth Cosign
        run: |
          cosign login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Sign Image keyless
        env:
          COSIGN_YES: true
        run: |
          cosign sign ${{ inputs.image-uri }} \
              -a sha=${{ github.sha }} \
              -a run_id=${{ github.run_id }} \
              -a run_attempt=${{ github.run_attempt }} \
              -a tag=${{ inputs.image-tag }} \
